// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nyiwwglvbwrzjwwaajtb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im55aXd3Z2x2Yndyemp3d2FhanRiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE5Njc0MjUsImV4cCI6MjA2NzU0MzQyNX0.YF99O6oGo-7tnuDPJGDutfd2YoxOpnAyrr26VnfFZvU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});